version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=xiaohongshu_assistant
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRES_IN=7d
      - TRIAL_CREDITS=3
      - MONTHLY_CREDITS=100
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=15
      - CUSTOM_CLAUDE_API_KEY=sk-RTGl4XXdYFzOmQBcFc0166466740412dAb4cF6FcC6EeC1F0
      - CUSTOM_CLAUDE_BASE_URL=https://dpapi.cn/v1
      - CUSTOM_CLAUDE_MODEL=claude-3-5-haiku-20241022
      - SILICONFLOW_API_KEY=sk-gkzxwmvpbtxdamblnspepmrwtkficdilkniqwoocahupdukw
      - SILICONFLOW_BASE_URL=https://api.siliconflow.cn/v1
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=xiaohongshu_assistant
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      timeout: 5s
      retries: 10
      interval: 10s
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge 